### ISSUE TITLE
Add custom fields to media manager

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks#1]
Clearly labeled, with description text letting them know where it will show up. 
 
Using [attachment_fields_to_edit](https://codex.wordpress.org/Plugin_API/Filter_Reference/attachment_fields_to_edit
) Following [TASL](https://wiki.creativecommons.org/wiki/Best_practices_for_attribution)

1. Title - TEXT 
2. Title Source - URL 
3. Author - TEXT
4. Author Source - URL
5. License - Selectbox (Content: https://github.com/pressbooks/pressbooks/blob/dev/inc/class-licensing.php#L39)

These fields would go after the author fields and before the licence drow-down menu.

6. Adapted by: TEXT
7.  Adapted by: URL

8. Figure: TEXT

**Comment by bdolor** [comment]
As a first pass, the base TASL (Title, Author, Source, License) has been added to the media manager: 

![image](https://user-images.githubusercontent.com/2048170/42524115-6994821a-8424-11e8-8392-c9a4ba9da5d2.png)

@josieg - to validate, go to Dashboard, edit any chapter, then click 'Add Media' — the fields will be on the right hand side. Once you enter values and select 'Insert into Post' the data should remain there then next time you visit the media manager by either the menu item on the left side or 'Add Media' button again.

**Comment by josiegray** [comment]
I found one problem:

I upload an image, add all of the attribution information, and insert it into a chapter. When I go back to the media manager, the licence is no longer selected, but the Title, Author, and Source content is still there. 

Also, the dropdown menu for the Licence field seems to extend off of the screen so it just looks like a textbox. 
<img width="314" alt="attributions box" src="https://user-images.githubusercontent.com/37554861/42526918-14b1762e-842c-11e8-8427-15e3e7c31722.PNG">

**Comment by bdolor** [comment]
excellent, thank you @josiegray - I noticed this just now as well. Please send back to the 'doing' column and once it's fixed I'll send it back to the 'validating' column.

**Comment by bdolor** [comment]
fixed via https://github.com/BCcampus/pressbooks/commit/0fb6a09d6f4036ccd42b3c2f2f67d3dffa7daf37

**Comment by josieg** [comment]
Will you be adding the other fields to the media manager in this sprint? (Author source (URL), adapted by (Text) + source (URL), and figure (Text)?
