### ISSUE TITLE
Logic of attribution fields

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks#10]
**Figure:** 
If figure field is empty, no link and no content in the caption area. 

If not empty, put figure label in the caption area and link it to the attribution statement at the bottom. 

Figure label at the bottom should link back to the image. (not to be confused with the html figure tag) 

Edge cases? 
Sentence logic?

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks/pull/14
@josieg to validate, play around with leaving some fields empty and look for any undesirable behaviour.
