### ISSUE TITLE
Add video and audio to extractIdFromMedia() 

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks#15]
Only looking for images right now, also look for video and audio. 

also, this function is generic enough to be a candidate for moving out of our class and be useful to other functions. look to incorporate into `inc/media/namespace.php`

**Comment by bdolor** [comment]
Currently, on the display side of capturing this metadata unlike images, there is no way to determine an audio or video post id from the markup that's generated: (wp-image-33), therefore this can only apply to images, for now

resolved via https://github.com/BCcampus/pressbooks/commit/0aaac9be9a407e4d72790313c5afd588f09ee865
