### ISSUE TITLE
Additional fields

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks#23]
so, we want to look at adding: 

- figure number field (maybe INT, maybe TEXT)
- author url (URL)

and derivative language
- adapted by field (TEXT)
- adapted by (URL)

a further requirement to adding these fields are that the must be registered meta and their input must be validated/sanitized.

**Comment by alex-418** [comment]
![all fields](https://user-images.githubusercontent.com/17072191/42787300-c5e4a876-890e-11e8-93ba-cb7c3b182578.png)

**Comment by alex-418** [comment]
Adding display and logic of new fields
