### ISSUE TITLE
Web: Display of attributions

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks#4]
Bottom of the page, in an UL with the title "Attributions" with markup similar to what's found in a "textbox". The goal is to adhere to accessibility standards. Attributions will order themselves in the order they appear on the page.

Minimal Language: 
Figure 1 "Image name" by "Author." Adapted by "Author." CC BY 4.0.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks/pull/14 
@josieg to test, set Media attributions checkbox value in global theme options, then add attributions to images in the media manager
![image](https://user-images.githubusercontent.com/2048170/42710585-6a205d0e-8699-11e8-9243-2f7a3a8c79e3.png)

**Comment by josieg** [comment]
Still working on testing, but here are the first things I see initially. Here is the page I'm testing in: [chapter 1](https://pressbooksdev.bccampus.ca/testing/chapter/chapter-1/)

Screen shot of attribution:
<img width="467" alt="attributions testing" src="https://user-images.githubusercontent.com/23706762/42711691-ac487b0e-869d-11e8-9fe4-04292f2dcb7b.PNG">

- The source link is being associated with the Author field, but it should be associated with the Title field (e.g., in the image, the link should be on "Diopside," not "Josie." (EDIT: Unless this field is supposed to be for the Author source and the Image source field is the one that will be added later.)
- Can we have the short form of licences display? (E.g. CC BY, CC BY-SA, CC BY-NC-SA, etc.)
- Can there be periods added after Author?  (E.g., Diopside by Josie. CC BY 4.0

**Comment by josieg** [comment]
Either this:
- When author is left blank, can you add a period after Title? (e.g. Diopside. CC BY 4.0)
- When title is left blank, can you capitalize the "By"? (e.g. By Josie. CC BY 4.0)

Or this:
Both Title and Author fields end with a period. (E.g. Diopside. By Josie. CC BY 4.0

**Comment by josieg** [comment]
Two more issues:

1. When I delete an image from a page and reload the webbook, the attribution statement that is associated with that image is not also deleted. It is still found in the chapter where that image was deleted from.

2. When I reorder the images on a page, click save, and open the chapter in the webbook, the attributions do not reorder themselves to match the order of the images on the page.

**Comment by bdolor** [comment]
nice catch...thank you Josie, for uncovering those

**Comment by bdolor** [comment]
the source link confusion and period placement is taken care of via https://github.com/BCcampus/pressbooks/commit/09c69388cc77125176503b580974d52f1f63cd40

**Comment by bdolor** [comment]
@josieg 
1. deleting images from a page is now treated as an event that will remove the corresponding attribution. 
2. Order of the images as they appear on the page will be reflected in the ordering of attribution statements. 
3. title is now linked instead of author
4. the value of the metakey has been changed to reflect a more semantic statement which means the metadata will have to be entered again in order to see it on the page.  

via https://github.com/BCcampus/pressbooks/commit/8081b57db0f151712f864014599efe4d49d178d2

**Comment by josieg** [comment]
Looks good!
