### ISSUE TITLE
Add "Adapted by:" as a custom field in the media manager

### ISSUE THREAD

**Issue by josiegray** [BCcampus/pressbooks#9]
Add another field in the media manager that allows people to demonstrate that the image is an adaptation. 
These fields would go after the author fields and before the licence drow-down menu.
1. Adapted by: TEXT
2. Adapted by: URL

**Comment by bdolor** [comment]
this is complete. 
![image](https://user-images.githubusercontent.com/2048170/42972144-609e9b50-8b63-11e8-9689-fa18e4e57448.png)
